"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.genres = void 0;
exports.genres = [
    "Rock",
    "Post Rock",
    "Pop",
    "BritPop",
    "Hip Hop",
    "Electronic",
    "Folk",
    "Jazz",
    "Classical",
    "Latin",
    "Reggae",
    "Blues",
    "Metal",
    "Punk",
    "Post Punk",
    "Hardcore Punk",
    "Post Hardcore",
    "Country",
    "R&B",
    "Soul",
    "Funk",
    "Disco",
    "New Age",
    "Ambient",
    "Soundtrack",
    "Indie",
    "Alternative",
    "Experimental",
    "Global",
];
