query contentQuery($relativePath: String!) {
  ...LayoutQueryFragment
  page(relativePath: $relativePath) {
    ...PageParts
  }
}

query pagesSegment {
  pageConnection {
    edges {
      node {
        segment
        locale
        id
        _sys {
          filename
          breadcrumbs
          relativePath
        }
      }
    }
  }
}
